spring:
  application:
    name: Spring-Boot-Collab
  datasource:
    url: jdbc:mysql://localhost:3306/collab_db?createDatabaseIfNotExist=true
    username: root
    password: password
    jpa:
      show-sql: true